import turtle

#head
turtle.penup()
turtle.forward(300)
turtle.pendown()
turtle.color("black","green")
turtle.begin_fill()
turtle.left(90)
turtle.forward(300)
turtle.left(90)
turtle.forward(600)
turtle.left(90)
turtle.forward(600)
turtle.left(90)
turtle.forward(600)
turtle.left(90)
turtle.forward(300)
turtle.end_fill()

#left eye
turtle.penup()
turtle.forward(60)
turtle.left(90)
turtle.forward(120)
turtle.pendown()
turtle.color("black","black")
turtle.begin_fill()
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.end_fill()

#right eye
turtle.penup()
turtle.right(90)
turtle.forward(240)
turtle.pendown()
turtle.color("black","black")
turtle.begin_fill()
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.end_fill()

#mouth
turtle.color("black", "black")
turtle.begin_fill()
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(180)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(180)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(120)
turtle.end_fill()

#move pen
turtle.penup()
turtle.forward(300)
turtle.pendown()
turtle.done()